### ISSUE TITLE
Some Questions about the data of KuaiSAR

### ISSUE THREAD

**Issue by melissamao** [Ethan00Si/SESREC-SIGIR-2023#1]
Thank you for your wonderful work! 
I tried to process the KuaiSAR dataset according to the steps stated in the paper, however, the models trained on my processed dataset are much lower on all the metrics than in the paper. I would like to know if this is due to problems with the steps I took to process the data, and I wonder if it would be convenient for you to disclose a copy of the processed ready-to-use KuaiSAR dataset?

**Comment by Ethan00Si** [comment]
The dataset used in this paper was not KuaiSAR. If you want to reproduce the results of SESREC on KuaiSAR, you can refer to the released data of [UniSAR](https://github.com/TengShi-RUC/UniSAR) (the processed ready-to-use data is available).   The performance will be similar to results reported in paper UniSAR. You need to tune hyper-parameters on KuaiSAR accordingly.

**Comment by zilinly** [comment]
The same question，follow UniSAR's method, but the dataset has also some difference with the expected data

**Comment by Ethan00Si** [comment]
The dataset used in this paper is not publicly available due to user privacy concerns. **The KuaiSAR dataset is not the dataset used in this paper.** So the performance might be different between these two datasets.

**Comment by zilinly** [comment]
but uniSAR‘ formats is also disfferent with the current data

**Comment by Ethan00Si** [comment]
They are two different works after all. I do not get what you want to express.

**Comment by zilinly** [comment]
want to get preprocess code of dataset on the SESrec
